name: Chabot.RabbitMq Nuget CI

on:
  push:
    tags:
      - 'chabot-rabbitmq-v*'

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
    uses: virtes/chabot/.github/workflows/nuget-ci-template.yml@master
    with:
      project-name: Chabot.RabbitMq
      tag-prefix: chabot-rabbitmq-v
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}