name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  build:
  
    env:
      TAG_NAME: "${{github.ref_name}}"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: GitHub Tag Name example
      run: |
       echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
       echo "Tag name from github.ref_name: ${{  github.ref_name }}"
       echo "Tag name from github.ref_name: ${{ TAG_NAME }}"
